# Generated by Django 4.0.5 on 2022-07-10 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_management_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu_items',
            name='item_category',
            field=models.CharField(max_length=250, verbose_name='CATEGORY'),
        ),
        migrations.AlterField(
            model_name='menu_items',
            name='item_name',
            field=models.CharField(max_length=250, verbose_name='NAME'),
        ),
        migrations.AlterField(
            model_name='menu_items',
            name='item_price',
            field=models.CharField(max_length=250, verbose_name='PRICE'),
        ),
    ]
