# Generated by Django 4.0.5 on 2022-07-11 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_management_app', '0002_alter_menu_items_item_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='billing_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateandtime', models.DateTimeField(max_length=250, verbose_name='Date and Time:')),
                ('signedBy', models.CharField(max_length=250, verbose_name='Signed By:')),
                ('items', models.CharField(max_length=250, verbose_name='Orders:')),
            ],
        ),
        migrations.AlterField(
            model_name='menu_items',
            name='item_category',
            field=models.CharField(max_length=250, verbose_name='CATEGORY:'),
        ),
        migrations.AlterField(
            model_name='menu_items',
            name='item_name',
            field=models.CharField(max_length=250, verbose_name='NAME:'),
        ),
        migrations.AlterField(
            model_name='menu_items',
            name='item_price',
            field=models.CharField(max_length=250, verbose_name='PRICE:'),
        ),
    ]
