# Generated by Django 4.0.5 on 2022-07-11 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_management_app', '0003_billing_details_alter_menu_items_item_category_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='billing_details',
            new_name='billing_detail',
        ),
        migrations.RenameModel(
            old_name='menu_items',
            new_name='menu_item',
        ),
    ]
