# Generated by Django 4.0.5 on 2022-07-11 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_management_app', '0004_rename_billing_details_billing_detail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing_detail',
            name='discount',
            field=models.CharField(default=0, max_length=250, verbose_name='Discount:'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='billing_detail',
            name='final_bill',
            field=models.CharField(default=0, max_length=250, verbose_name='Net Amount:'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='billing_detail',
            name='price',
            field=models.CharField(default=0, max_length=250, verbose_name='Price:'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='billing_detail',
            name='tax',
            field=models.CharField(default=0, max_length=250, verbose_name='Tax:'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='billing_detail',
            name='total_amount',
            field=models.CharField(default=0, max_length=25, verbose_name='Bill Amount:'),
            preserve_default=False,
        ),
    ]
