# Generated by Django 4.0.5 on 2022-07-14 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_management_app', '0006_billing_detail_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='table_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateandtime', models.DateTimeField(max_length=250, verbose_name='Date and Time:')),
                ('createdBy', models.CharField(max_length=250, verbose_name='Created By:')),
                ('table_no', models.IntegerField(verbose_name='Table No.:')),
                ('table_status', models.CharField(max_length=250, verbose_name='Table Status:')),
                ('table_status_checked_by', models.CharField(max_length=250, verbose_name='Status Checked By:')),
            ],
        ),
    ]
