# Generated by Django 4.0.5 on 2022-07-15 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_management_app', '0007_table_detail'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateandtime', models.DateTimeField(max_length=250, verbose_name='Order Date and Time:')),
                ('createdBy', models.CharField(max_length=250, verbose_name='Order Created By:')),
                ('table_no', models.IntegerField(verbose_name='Table No.:')),
                ('items', models.CharField(max_length=250, verbose_name='Order Items:')),
                ('order_status', models.CharField(max_length=250, verbose_name='Status')),
                ('total_bill', models.IntegerField(max_length=250, verbose_name='Total Bill')),
                ('paid_with', models.CharField(max_length=250, verbose_name='Paid By:')),
            ],
        ),
        migrations.AlterField(
            model_name='table_detail',
            name='dateandtime',
            field=models.DateTimeField(max_length=250, verbose_name='Created At:'),
        ),
    ]
