# Generated by Django 4.0.5 on 2022-07-15 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_management_app', '0008_order_alter_table_detail_dateandtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='quantity',
            field=models.CharField(default=0, max_length=250, verbose_name='Quantity:'),
            preserve_default=False,
        ),
    ]
